error handling for component create

diff --git a/gg b/gg
--- a/gg
+++ b/gg
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.5 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.2.10 (https://bashly.dev)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -711,15 +711,6 @@ inspect_args() {
     echo args: none
   fi
 
-  if ((${#other_args[@]})); then
-    echo
-    echo other_args:
-    echo "- \${other_args[*]} = ${other_args[*]}"
-    for i in "${!other_args[@]}"; do
-      echo "- \${other_args[$i]} = ${other_args[$i]}"
-    done
-  fi
-
   if ((${#deps[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
     echo
@@ -1157,9 +1148,21 @@ gg_component_create_command() {
   COMPONENT_VERSION=${args[component_version]}
   COMPONENT_NAME=$(yq ".componentName" $config_file)
 
+  COMPONENT_S3_BUCKET=$(yq ".s3BucketName" $config_file)
   RECIPE_FILE_PATH=$recipes_dir_path/recipe-$COMPONENT_VERSION.yaml
 
   log DEBUG "Using recipe - $RECIPE_FILE_PATH"
+
+  # Check if the component artifact exists in S3
+  S3_PATH="s3://$COMPONENT_S3_BUCKET/artifacts/$COMPONENT_NAME/$COMPONENT_VERSION/files.zip"
+  log INFO "Checking if component artifact exists at $S3_PATH"
+  if ! aws s3 ls $S3_PATH > /dev/null 2>&1; then
+    log ERROR "Component artifact not found at $S3_PATH"
+    log ERROR "Please run 'gdc component push $COMPONENT_VERSION' first"
+    exit 1
+  else
+    log INFO "Component artifact found at $S3_PATH"
+  fi
 
   # Create component version
   cmd1=(
@@ -1175,7 +1178,6 @@ gg_component_create_command() {
   echo ""
 
   # Check the status of the create request
-
   cmd2=(
     aws greengrassv2 describe-component
     --arn arn:aws:greengrass:$AWS_REGION:$AWS_ACCOUNT:components:$COMPONENT_NAME:versions:$COMPONENT_VERSION
@@ -1183,11 +1185,23 @@ gg_component_create_command() {
   )
   log INFO "Checking the component status"
   log DEBUG "Executing - ${cmd2[*]}"
+
   echo ""
-  "${cmd2[@]}" | yq
+  #"${cmd2[@]}" | yq
+
+  # Error handling
+  if ! describe_result=$("${cmd2[@]}" 2>&1); then
+    log ERROR "Failed to describe component: $COMPONENT_NAME:$COMPONENT_VERSION"
+    echo "$describe_result"
+    exit 1
+  fi
+
+  describe_output=$(echo "$describe_result" | yq)
+  echo "$describe_output"
   echo ""
 
-  log INFO "$COMPONENT_NAME - $COMPONENT_VERSION created"
+  log INFO "$COMPONENT_NAME - $COMPONENT_VERSION created successfully"
+
 }
 
 # :command.function
@@ -1575,9 +1589,6 @@ gg_local_deployment_deploy_command() {
   "${cmd1[@]}" | yq || log ERROR "Failed to parse the output with yq"
   echo ""
 
-  # TODO - Remove the local component
-  # sudo /greengrass/v2/bin/greengrass-cli deployment create --recipeDir component/recipes/ --remove local-deploy-test
-
 }
 
 # :command.function
@@ -1664,19 +1675,26 @@ parse_requirements() {
   fi
 
   # :command.dependencies_filter
-  if command -v aws >/dev/null 2>&1; then
-    deps['aws']="$(command -v aws | head -n1)"
-  else
+  missing_deps=
+  # :dependency.filter
+  if ! command -v aws >/dev/null 2>&1; then
     printf "missing dependency: aws\n" >&2
-    printf "%s\n" "See https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html for setup instructions." >&2
-    exit 1
+    printf "%s\n\n" "See https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html for setup instructions." >&2
+    missing_deps=1
+  else
+    deps['aws']="$(command -v aws | head -n1)"
   fi
 
-  if command -v yq >/dev/null 2>&1; then
-    deps['yq']="$(command -v yq | head -n1)"
-  else
+  # :dependency.filter
+  if ! command -v yq >/dev/null 2>&1; then
     printf "missing dependency: yq\n" >&2
-    printf "%s\n" "See https://mikefarah.gitbook.io/yq#install for setup instructions." >&2
+    printf "%s\n\n" "See https://mikefarah.gitbook.io/yq#install for setup instructions." >&2
+    missing_deps=1
+  else
+    deps['yq']="$(command -v yq | head -n1)"
+  fi
+
+  if [[ -n $missing_deps ]]; then
     exit 1
   fi
 
@@ -2973,11 +2991,17 @@ gg_local_deployment_parse_requirements() {
   done
 
   # :command.dependencies_filter
-  if command -v /greengrass/v2/bin/greengrass-cli >/dev/null 2>&1; then
-    deps['/greengrass/v2/bin/greengrass-cli']="$(command -v /greengrass/v2/bin/greengrass-cli | head -n1)"
-  else
+  missing_deps=
+  # :dependency.filter
+  if ! command -v /greengrass/v2/bin/greengrass-cli >/dev/null 2>&1; then
     printf "missing dependency: /greengrass/v2/bin/greengrass-cli\n" >&2
-    printf "%s\n" "See https://docs.aws.amazon.com/greengrass/v2/developerguide/install-gg-cli.html for installation and setup instructions." >&2
+    printf "%s\n\n" "See https://docs.aws.amazon.com/greengrass/v2/developerguide/install-gg-cli.html for installation and setup instructions." >&2
+    missing_deps=1
+  else
+    deps['/greengrass/v2/bin/greengrass-cli']="$(command -v /greengrass/v2/bin/greengrass-cli | head -n1)"
+  fi
+
+  if [[ -n $missing_deps ]]; then
     exit 1
   fi
 
@@ -3241,40 +3265,39 @@ gg_local_deployment_status_parse_requirements() {
 
 # :command.initialize
 initialize() {
-  version="1.0.0"
-  long_usage=''
+  declare -g version="1.0.0"
   set -e
 
   # :command.variables
   # :variable.definition
-  command_name="gg"
+  declare -g command_name="gg"
 
   # :variable.definition
-  config_file="config.yaml"
+  declare -g config_file="config.yaml"
 
   # :variable.definition
-  artifacts_dir_path="component/artifacts"
+  declare -g artifacts_dir_path="component/artifacts"
 
   # :variable.definition
-  recipes_dir_path="component/recipes"
+  declare -g recipes_dir_path="component/recipes"
 
   # :variable.definition
-  src_dir_path="component/src"
+  declare -g src_dir_path="component/src"
 
   # :variable.definition
-  deployment_dir_path="deployment"
+  declare -g deployment_dir_path="deployment"
 
   # :variable.definition
-  deployment_yaml_path="deployment/deployment.yaml"
+  declare -g deployment_yaml_path="deployment/deployment.yaml"
 
   # :variable.definition
-  recipe_yaml_path="component/recipe.yaml"
+  declare -g recipe_yaml_path="component/recipe.yaml"
 
   # :variable.definition
-  template_dir_path="templates"
+  declare -g template_dir_path="templates"
 
   # :variable.definition
-  default_template="python/hello-world"
+  declare -g default_template="python/hello-world"
 
   # :command.environment_variables_default
   export MESSAGE_LEVEL="${MESSAGE_LEVEL:-INFO}"
@@ -3283,11 +3306,13 @@ initialize() {
 
 # :command.run
 run() {
-  declare -A args=()
-  declare -A deps=()
-  declare -a other_args=()
-  declare -a env_var_names=()
-  declare -a input=()
+  # :command.globals
+  declare -g long_usage=''
+  declare -g -A args=()
+  declare -g -A deps=()
+  declare -g -a env_var_names=()
+  declare -g -a input=()
+
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
@@ -3316,5 +3341,7 @@ run() {
   esac
 }
 
-initialize
-run "$@"
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+  initialize
+  run "$@"
+fi
